export const mockBookings = [
  {
    id: "WX4S5MB",
    movieName: "Kudumbasthan",
    type: "2D",
    date: "Sun, 26 Jan 2025",
    time: "7:00 PM",
    theater: "Rohini Silver Screens: Koyambedu",
    seats: "Platinum - F14, F15, F16, F17, F18, F19",
    screen: "ROHINI",
    totalAmount: 1363.2,
    bookingDate: "Jan 26 2025 02:26PM",
    paymentMethod: "Credit/Debit Card",
    ticketType: "Pick Up",
  },
  {
    id: "MG7H9NB",
    movieName: "Madha Gaja Raja",
    type: "2D",
    date: "Mon, 13 Jan 2025",
    time: "2:45 PM",
    theater: "Janas Cinemas: Maghalakshmi Plaazaa Villupuram",
    seats: "ELITE - C3",
    screen: "SCREEN 3",
    totalAmount: 155.1,
    bookingDate: "Jan 13 2025 10:15AM",
    paymentMethod: "Credit/Debit Card",
    ticketType: "M-Ticket",
  },
  {
    id: "WX4S5MB",
    movieName: "Kudumbasthan",
    type: "2D",
    date: "Sun, 26 Jan 2025",
    time: "7:00 PM",
    theater: "Rohini Silver Screens: Koyambedu",
    seats: "Platinum - F14, F15, F16, F17, F18, F19",
    screen: "ROHINI",
    totalAmount: 1363.2,
    bookingDate: "Jan 26 2025 02:26PM",
    paymentMethod: "Credit/Debit Card",
    ticketType: "Pick Up",
  },
  {
    id: "MG7H9NB",
    movieName: "Madha Gaja Raja",
    type: "2D",
    date: "Mon, 13 Jan 2025",
    time: "2:45 PM",
    theater: "Janas Cinemas: Maghalakshmi Plaazaa Villupuram",
    seats: "ELITE - C3",
    screen: "SCREEN 3",
    totalAmount: 155.1,
    bookingDate: "Jan 13 2025 10:15AM",
    paymentMethod: "Credit/Debit Card",
    ticketType: "M-Ticket",
  },
  {
    id: "WX4S5MB",
    movieName: "Kudumbasthan",
    type: "2D",
    date: "Sun, 26 Jan 2025",
    time: "7:00 PM",
    theater: "Rohini Silver Screens: Koyambedu",
    seats: "Platinum - F14, F15, F16, F17, F18, F19",
    screen: "ROHINI",
    totalAmount: 1363.2,
    bookingDate: "Jan 26 2025 02:26PM",
    paymentMethod: "Credit/Debit Card",
    ticketType: "Pick Up",
  },
  {
    id: "MG7H9NB",
    movieName: "Madha Gaja Raja",
    type: "2D",
    date: "Mon, 13 Jan 2025",
    time: "2:45 PM",
    theater: "Janas Cinemas: Maghalakshmi Plaazaa Villupuram",
    seats: "ELITE - C3",
    screen: "SCREEN 3",
    totalAmount: 155.1,
    bookingDate: "Jan 13 2025 10:15AM",
    paymentMethod: "Credit/Debit Card",
    ticketType: "M-Ticket",
  },
];
