export const showDetails = {
  movieName: "SALAAR PART-I CEASEFIRE",
  theatreDetail: "PVR INOX Velachery: Grand Mall, velachery",
  showDetail: "Sunday, 26 Jan, 10.30 AM",
};

export const showSeatlayout = [
  {
    showSeatMappingId: 1,
    seatNumber: "A1",
    seatRow: 1,
    seatCol: 1,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 2,
    seatNumber: "A2",
    seatRow: 1,
    seatCol: 2,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 3,
    seatNumber: "A3",
    seatRow: 1,
    seatCol: 3,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 4,
    seatNumber: "A4",
    seatRow: 1,
    seatCol: 4,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 5,
    seatNumber: "A5",
    seatRow: 1,
    seatCol: 5,
    seatType: "PREMIUM",
    seatStatus: "BLOCKED",
    price: 180.0,
  },
  {
    showSeatMappingId: 6,
    seatNumber: "A6",
    seatRow: 1,
    seatCol: 6,
    seatType: "PREMIUM",
    seatStatus: "BLOCKED",
    price: 180.0,
  },
  {
    showSeatMappingId: 7,
    seatNumber: "A7",
    seatRow: 1,
    seatCol: 7,
    seatType: "PREMIUM",
    seatStatus: "BLOCKED",
    price: 180.0,
  },
  {
    showSeatMappingId: 8,
    seatNumber: "A8",
    seatRow: 1,
    seatCol: 8,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 9,
    seatNumber: "A9",
    seatRow: 1,
    seatCol: 9,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 10,
    seatNumber: "A10",
    seatRow: 1,
    seatCol: 10,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 11,
    seatNumber: "A11",
    seatRow: 1,
    seatCol: 11,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 12,
    seatNumber: "A12",
    seatRow: 1,
    seatCol: 12,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 13,
    seatNumber: "A13",
    seatRow: 1,
    seatCol: 13,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 14,
    seatNumber: "A14",
    seatRow: 1,
    seatCol: 14,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 15,
    seatNumber: "A15",
    seatRow: 1,
    seatCol: 15,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 16,
    seatNumber: "A16",
    seatRow: 1,
    seatCol: 16,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 17,
    seatNumber: "A17",
    seatRow: 1,
    seatCol: 17,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 18,
    seatNumber: "A18",
    seatRow: 1,
    seatCol: 18,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 19,
    seatNumber: "A19",
    seatRow: 1,
    seatCol: 19,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 20,
    seatNumber: "A20",
    seatRow: 1,
    seatCol: 20,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 21,
    seatNumber: "B1",
    seatRow: 2,
    seatCol: 1,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 22,
    seatNumber: "B2",
    seatRow: 2,
    seatCol: 2,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 23,
    seatNumber: "B3",
    seatRow: 2,
    seatCol: 3,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 24,
    seatNumber: "B4",
    seatRow: 2,
    seatCol: 4,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 25,
    seatNumber: "B5",
    seatRow: 2,
    seatCol: 5,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 26,
    seatNumber: "B6",
    seatRow: 2,
    seatCol: 6,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 27,
    seatNumber: "B7",
    seatRow: 2,
    seatCol: 7,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 28,
    seatNumber: "B8",
    seatRow: 2,
    seatCol: 8,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 29,
    seatNumber: "B9",
    seatRow: 2,
    seatCol: 9,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 30,
    seatNumber: "B10",
    seatRow: 2,
    seatCol: 10,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 31,
    seatNumber: "B11",
    seatRow: 2,
    seatCol: 11,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 32,
    seatNumber: "B12",
    seatRow: 2,
    seatCol: 12,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 33,
    seatNumber: "B13",
    seatRow: 2,
    seatCol: 13,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 34,
    seatNumber: "B14",
    seatRow: 2,
    seatCol: 14,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 35,
    seatNumber: "B15",
    seatRow: 2,
    seatCol: 15,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 36,
    seatNumber: "B16",
    seatRow: 2,
    seatCol: 16,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 37,
    seatNumber: "B17",
    seatRow: 2,
    seatCol: 17,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 38,
    seatNumber: "B18",
    seatRow: 2,
    seatCol: 18,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 39,
    seatNumber: "B19",
    seatRow: 2,
    seatCol: 19,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 40,
    seatNumber: "B20",
    seatRow: 2,
    seatCol: 20,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 41,
    seatNumber: "C1",
    seatRow: 3,
    seatCol: 1,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 42,
    seatNumber: "C2",
    seatRow: 3,
    seatCol: 2,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 43,
    seatNumber: "C3",
    seatRow: 3,
    seatCol: 3,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 44,
    seatNumber: "C4",
    seatRow: 3,
    seatCol: 4,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 45,
    seatNumber: "C5",
    seatRow: 3,
    seatCol: 5,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 46,
    seatNumber: "C6",
    seatRow: 3,
    seatCol: 6,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 47,
    seatNumber: "C7",
    seatRow: 3,
    seatCol: 7,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 48,
    seatNumber: "C8",
    seatRow: 3,
    seatCol: 8,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 49,
    seatNumber: "C9",
    seatRow: 3,
    seatCol: 9,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 50,
    seatNumber: "C10",
    seatRow: 3,
    seatCol: 10,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 51,
    seatNumber: "C11",
    seatRow: 3,
    seatCol: 11,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 52,
    seatNumber: "C12",
    seatRow: 3,
    seatCol: 12,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 53,
    seatNumber: "C13",
    seatRow: 3,
    seatCol: 13,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 54,
    seatNumber: "C14",
    seatRow: 3,
    seatCol: 14,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 55,
    seatNumber: "C15",
    seatRow: 3,
    seatCol: 15,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 56,
    seatNumber: "C16",
    seatRow: 3,
    seatCol: 16,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 57,
    seatNumber: "C17",
    seatRow: 3,
    seatCol: 17,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 58,
    seatNumber: "C18",
    seatRow: 3,
    seatCol: 18,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 59,
    seatNumber: "C19",
    seatRow: 3,
    seatCol: 19,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 60,
    seatNumber: "C20",
    seatRow: 3,
    seatCol: 20,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 61,
    seatNumber: "D1",
    seatRow: 4,
    seatCol: 1,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 62,
    seatNumber: "D2",
    seatRow: 4,
    seatCol: 2,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 63,
    seatNumber: "D3",
    seatRow: 4,
    seatCol: 3,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 64,
    seatNumber: "D4",
    seatRow: 4,
    seatCol: 4,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 65,
    seatNumber: "D5",
    seatRow: 4,
    seatCol: 5,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 66,
    seatNumber: "D6",
    seatRow: 4,
    seatCol: 6,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 67,
    seatNumber: "D7",
    seatRow: 4,
    seatCol: 7,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 68,
    seatNumber: "D8",
    seatRow: 4,
    seatCol: 8,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 69,
    seatNumber: "D9",
    seatRow: 4,
    seatCol: 9,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 70,
    seatNumber: "D10",
    seatRow: 4,
    seatCol: 10,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 71,
    seatNumber: "D11",
    seatRow: 4,
    seatCol: 11,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 72,
    seatNumber: "D12",
    seatRow: 4,
    seatCol: 12,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 73,
    seatNumber: "D13",
    seatRow: 4,
    seatCol: 13,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 74,
    seatNumber: "D14",
    seatRow: 4,
    seatCol: 14,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 75,
    seatNumber: "D15",
    seatRow: 4,
    seatCol: 15,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 76,
    seatNumber: "D16",
    seatRow: 4,
    seatCol: 16,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 77,
    seatNumber: "D17",
    seatRow: 4,
    seatCol: 17,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 78,
    seatNumber: "D18",
    seatRow: 4,
    seatCol: 18,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 79,
    seatNumber: "D19",
    seatRow: 4,
    seatCol: 19,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 80,
    seatNumber: "D20",
    seatRow: 4,
    seatCol: 20,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 81,
    seatNumber: "E1",
    seatRow: 5,
    seatCol: 1,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 82,
    seatNumber: "E2",
    seatRow: 5,
    seatCol: 2,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 83,
    seatNumber: "E3",
    seatRow: 5,
    seatCol: 3,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 84,
    seatNumber: "E4",
    seatRow: 5,
    seatCol: 4,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 85,
    seatNumber: "E5",
    seatRow: 5,
    seatCol: 5,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 86,
    seatNumber: "E6",
    seatRow: 5,
    seatCol: 6,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 87,
    seatNumber: "E7",
    seatRow: 5,
    seatCol: 7,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 88,
    seatNumber: "E8",
    seatRow: 5,
    seatCol: 8,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 89,
    seatNumber: "E9",
    seatRow: 5,
    seatCol: 9,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 90,
    seatNumber: "E10",
    seatRow: 5,
    seatCol: 10,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 91,
    seatNumber: "E11",
    seatRow: 5,
    seatCol: 11,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 92,
    seatNumber: "E12",
    seatRow: 5,
    seatCol: 12,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 93,
    seatNumber: "E13",
    seatRow: 5,
    seatCol: 13,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 94,
    seatNumber: "E14",
    seatRow: 5,
    seatCol: 14,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 95,
    seatNumber: "E15",
    seatRow: 5,
    seatCol: 15,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 96,
    seatNumber: "E16",
    seatRow: 5,
    seatCol: 16,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 97,
    seatNumber: "E17",
    seatRow: 5,
    seatCol: 17,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 98,
    seatNumber: "E18",
    seatRow: 5,
    seatCol: 18,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 99,
    seatNumber: "E19",
    seatRow: 5,
    seatCol: 19,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 100,
    seatNumber: "E20",
    seatRow: 5,
    seatCol: 20,
    seatType: "PREMIUM",
    seatStatus: "AVAILABLE",
    price: 180.0,
  },
  {
    showSeatMappingId: 101,
    seatNumber: "F1",
    seatRow: 6,
    seatCol: 1,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 102,
    seatNumber: "F2",
    seatRow: 6,
    seatCol: 2,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 103,
    seatNumber: "F3",
    seatRow: 6,
    seatCol: 3,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 104,
    seatNumber: "F4",
    seatRow: 6,
    seatCol: 4,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 105,
    seatNumber: "F5",
    seatRow: 6,
    seatCol: 5,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 106,
    seatNumber: "F6",
    seatRow: 6,
    seatCol: 6,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 107,
    seatNumber: "F7",
    seatRow: 6,
    seatCol: 7,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 108,
    seatNumber: "F8",
    seatRow: 6,
    seatCol: 8,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 109,
    seatNumber: "F9",
    seatRow: 6,
    seatCol: 9,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 110,
    seatNumber: "F10",
    seatRow: 6,
    seatCol: 10,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 111,
    seatNumber: "F11",
    seatRow: 6,
    seatCol: 11,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 112,
    seatNumber: "F12",
    seatRow: 6,
    seatCol: 12,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 113,
    seatNumber: "F13",
    seatRow: 6,
    seatCol: 13,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 114,
    seatNumber: "F14",
    seatRow: 6,
    seatCol: 14,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 115,
    seatNumber: "F15",
    seatRow: 6,
    seatCol: 15,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 116,
    seatNumber: "F16",
    seatRow: 6,
    seatCol: 16,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 117,
    seatNumber: "F17",
    seatRow: 6,
    seatCol: 17,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 118,
    seatNumber: "F18",
    seatRow: 6,
    seatCol: 18,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 119,
    seatNumber: "F19",
    seatRow: 6,
    seatCol: 19,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 120,
    seatNumber: "F20",
    seatRow: 6,
    seatCol: 20,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 121,
    seatNumber: "G1",
    seatRow: 7,
    seatCol: 1,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 122,
    seatNumber: "G2",
    seatRow: 7,
    seatCol: 2,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 123,
    seatNumber: "G3",
    seatRow: 7,
    seatCol: 3,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 124,
    seatNumber: "G4",
    seatRow: 7,
    seatCol: 4,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 125,
    seatNumber: "G5",
    seatRow: 7,
    seatCol: 5,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 126,
    seatNumber: "G6",
    seatRow: 7,
    seatCol: 6,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 127,
    seatNumber: "G7",
    seatRow: 7,
    seatCol: 7,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 128,
    seatNumber: "G8",
    seatRow: 7,
    seatCol: 8,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 129,
    seatNumber: "G9",
    seatRow: 7,
    seatCol: 9,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 130,
    seatNumber: "G10",
    seatRow: 7,
    seatCol: 10,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 131,
    seatNumber: "G11",
    seatRow: 7,
    seatCol: 11,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 132,
    seatNumber: "G12",
    seatRow: 7,
    seatCol: 12,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 133,
    seatNumber: "G13",
    seatRow: 7,
    seatCol: 13,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 134,
    seatNumber: "G14",
    seatRow: 7,
    seatCol: 14,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 135,
    seatNumber: "G15",
    seatRow: 7,
    seatCol: 15,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 136,
    seatNumber: "G16",
    seatRow: 7,
    seatCol: 16,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 137,
    seatNumber: "G17",
    seatRow: 7,
    seatCol: 17,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 138,
    seatNumber: "G18",
    seatRow: 7,
    seatCol: 18,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 139,
    seatNumber: "G19",
    seatRow: 7,
    seatCol: 19,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 140,
    seatNumber: "G20",
    seatRow: 7,
    seatCol: 20,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 141,
    seatNumber: "H1",
    seatRow: 8,
    seatCol: 1,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 142,
    seatNumber: "H2",
    seatRow: 8,
    seatCol: 2,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 143,
    seatNumber: "H3",
    seatRow: 8,
    seatCol: 3,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 144,
    seatNumber: "H4",
    seatRow: 8,
    seatCol: 4,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 145,
    seatNumber: "H5",
    seatRow: 8,
    seatCol: 5,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 146,
    seatNumber: "H6",
    seatRow: 8,
    seatCol: 6,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 147,
    seatNumber: "H7",
    seatRow: 8,
    seatCol: 7,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 148,
    seatNumber: "H8",
    seatRow: 8,
    seatCol: 8,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 149,
    seatNumber: "H9",
    seatRow: 8,
    seatCol: 9,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 150,
    seatNumber: "H10",
    seatRow: 8,
    seatCol: 10,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 151,
    seatNumber: "H11",
    seatRow: 8,
    seatCol: 11,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 152,
    seatNumber: "H12",
    seatRow: 8,
    seatCol: 12,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 153,
    seatNumber: "H13",
    seatRow: 8,
    seatCol: 13,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 154,
    seatNumber: "H14",
    seatRow: 8,
    seatCol: 14,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 155,
    seatNumber: "H15",
    seatRow: 8,
    seatCol: 15,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 156,
    seatNumber: "H16",
    seatRow: 8,
    seatCol: 16,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 157,
    seatNumber: "H17",
    seatRow: 8,
    seatCol: 17,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 158,
    seatNumber: "H18",
    seatRow: 8,
    seatCol: 18,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 159,
    seatNumber: "H19",
    seatRow: 8,
    seatCol: 19,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 160,
    seatNumber: "H20",
    seatRow: 8,
    seatCol: 20,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 161,
    seatNumber: "I1",
    seatRow: 9,
    seatCol: 1,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 162,
    seatNumber: "I2",
    seatRow: 9,
    seatCol: 2,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 163,
    seatNumber: "I3",
    seatRow: 9,
    seatCol: 3,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 164,
    seatNumber: "I4",
    seatRow: 9,
    seatCol: 4,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 165,
    seatNumber: "I5",
    seatRow: 9,
    seatCol: 5,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 166,
    seatNumber: "I6",
    seatRow: 9,
    seatCol: 6,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 167,
    seatNumber: "I7",
    seatRow: 9,
    seatCol: 7,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 168,
    seatNumber: "I8",
    seatRow: 9,
    seatCol: 8,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 169,
    seatNumber: "I9",
    seatRow: 9,
    seatCol: 9,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 170,
    seatNumber: "I10",
    seatRow: 9,
    seatCol: 10,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 171,
    seatNumber: "I11",
    seatRow: 9,
    seatCol: 11,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 172,
    seatNumber: "I12",
    seatRow: 9,
    seatCol: 12,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 173,
    seatNumber: "I13",
    seatRow: 9,
    seatCol: 13,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 174,
    seatNumber: "I14",
    seatRow: 9,
    seatCol: 14,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 175,
    seatNumber: "I15",
    seatRow: 9,
    seatCol: 15,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 176,
    seatNumber: "I16",
    seatRow: 9,
    seatCol: 16,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 177,
    seatNumber: "I17",
    seatRow: 9,
    seatCol: 17,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 178,
    seatNumber: "I18",
    seatRow: 9,
    seatCol: 18,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 179,
    seatNumber: "I19",
    seatRow: 9,
    seatCol: 19,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 180,
    seatNumber: "I20",
    seatRow: 9,
    seatCol: 20,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 181,
    seatNumber: "J1",
    seatRow: 10,
    seatCol: 1,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 182,
    seatNumber: "J2",
    seatRow: 10,
    seatCol: 2,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 183,
    seatNumber: "J3",
    seatRow: 10,
    seatCol: 3,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 184,
    seatNumber: "J4",
    seatRow: 10,
    seatCol: 4,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 185,
    seatNumber: "J5",
    seatRow: 10,
    seatCol: 5,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 186,
    seatNumber: "J6",
    seatRow: 10,
    seatCol: 6,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 187,
    seatNumber: "J7",
    seatRow: 10,
    seatCol: 7,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 188,
    seatNumber: "J8",
    seatRow: 10,
    seatCol: 8,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 189,
    seatNumber: "J9",
    seatRow: 10,
    seatCol: 9,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 190,
    seatNumber: "J10",
    seatRow: 10,
    seatCol: 10,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 191,
    seatNumber: "J11",
    seatRow: 10,
    seatCol: 11,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 192,
    seatNumber: "J12",
    seatRow: 10,
    seatCol: 12,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 193,
    seatNumber: "J13",
    seatRow: 10,
    seatCol: 13,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 194,
    seatNumber: "J14",
    seatRow: 10,
    seatCol: 14,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 195,
    seatNumber: "J15",
    seatRow: 10,
    seatCol: 15,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 196,
    seatNumber: "J16",
    seatRow: 10,
    seatCol: 16,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 197,
    seatNumber: "J17",
    seatRow: 10,
    seatCol: 17,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 198,
    seatNumber: "J18",
    seatRow: 10,
    seatCol: 18,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 199,
    seatNumber: "J19",
    seatRow: 10,
    seatCol: 19,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 200,
    seatNumber: "J20",
    seatRow: 10,
    seatCol: 20,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 201,
    seatNumber: "K1",
    seatRow: 11,
    seatCol: 1,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 202,
    seatNumber: "K2",
    seatRow: 11,
    seatCol: 2,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 203,
    seatNumber: "K3",
    seatRow: 11,
    seatCol: 3,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 204,
    seatNumber: "K4",
    seatRow: 11,
    seatCol: 4,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 205,
    seatNumber: "K5",
    seatRow: 11,
    seatCol: 5,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 206,
    seatNumber: "K6",
    seatRow: 11,
    seatCol: 6,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 207,
    seatNumber: "K7",
    seatRow: 11,
    seatCol: 7,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 208,
    seatNumber: "K8",
    seatRow: 11,
    seatCol: 8,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 209,
    seatNumber: "K9",
    seatRow: 11,
    seatCol: 9,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 210,
    seatNumber: "K10",
    seatRow: 11,
    seatCol: 10,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 211,
    seatNumber: "K11",
    seatRow: 11,
    seatCol: 11,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 212,
    seatNumber: "K12",
    seatRow: 11,
    seatCol: 12,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 213,
    seatNumber: "K13",
    seatRow: 11,
    seatCol: 13,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 214,
    seatNumber: "K14",
    seatRow: 11,
    seatCol: 14,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 215,
    seatNumber: "K15",
    seatRow: 11,
    seatCol: 15,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 216,
    seatNumber: "K16",
    seatRow: 11,
    seatCol: 16,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 217,
    seatNumber: "K17",
    seatRow: 11,
    seatCol: 17,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 218,
    seatNumber: "K18",
    seatRow: 11,
    seatCol: 18,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 219,
    seatNumber: "K19",
    seatRow: 11,
    seatCol: 19,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 220,
    seatNumber: "K20",
    seatRow: 11,
    seatCol: 20,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 221,
    seatNumber: "L1",
    seatRow: 12,
    seatCol: 1,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 222,
    seatNumber: "L2",
    seatRow: 12,
    seatCol: 2,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 223,
    seatNumber: "L3",
    seatRow: 12,
    seatCol: 3,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 224,
    seatNumber: "L4",
    seatRow: 12,
    seatCol: 4,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 225,
    seatNumber: "L5",
    seatRow: 12,
    seatCol: 5,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 226,
    seatNumber: "L6",
    seatRow: 12,
    seatCol: 6,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 227,
    seatNumber: "L7",
    seatRow: 12,
    seatCol: 7,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 228,
    seatNumber: "L8",
    seatRow: 12,
    seatCol: 8,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 229,
    seatNumber: "L9",
    seatRow: 12,
    seatCol: 9,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 230,
    seatNumber: "L10",
    seatRow: 12,
    seatCol: 10,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 231,
    seatNumber: "L11",
    seatRow: 12,
    seatCol: 11,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 232,
    seatNumber: "L12",
    seatRow: 12,
    seatCol: 12,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 233,
    seatNumber: "L13",
    seatRow: 12,
    seatCol: 13,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 234,
    seatNumber: "L14",
    seatRow: 12,
    seatCol: 14,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 235,
    seatNumber: "L15",
    seatRow: 12,
    seatCol: 15,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 236,
    seatNumber: "L16",
    seatRow: 12,
    seatCol: 16,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 237,
    seatNumber: "L17",
    seatRow: 12,
    seatCol: 17,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 238,
    seatNumber: "L18",
    seatRow: 12,
    seatCol: 18,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 239,
    seatNumber: "L19",
    seatRow: 12,
    seatCol: 19,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 240,
    seatNumber: "L20",
    seatRow: 12,
    seatCol: 20,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 241,
    seatNumber: "M1",
    seatRow: 13,
    seatCol: 1,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 242,
    seatNumber: "M2",
    seatRow: 13,
    seatCol: 2,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 243,
    seatNumber: "M3",
    seatRow: 13,
    seatCol: 3,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 244,
    seatNumber: "M4",
    seatRow: 13,
    seatCol: 4,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 245,
    seatNumber: "M5",
    seatRow: 13,
    seatCol: 5,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 246,
    seatNumber: "M6",
    seatRow: 13,
    seatCol: 6,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 247,
    seatNumber: "M7",
    seatRow: 13,
    seatCol: 7,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 248,
    seatNumber: "M8",
    seatRow: 13,
    seatCol: 8,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 249,
    seatNumber: "M9",
    seatRow: 13,
    seatCol: 9,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 250,
    seatNumber: "M10",
    seatRow: 13,
    seatCol: 10,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 251,
    seatNumber: "M11",
    seatRow: 13,
    seatCol: 11,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 252,
    seatNumber: "M12",
    seatRow: 13,
    seatCol: 12,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 253,
    seatNumber: "M13",
    seatRow: 13,
    seatCol: 13,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 254,
    seatNumber: "M14",
    seatRow: 13,
    seatCol: 14,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 255,
    seatNumber: "M15",
    seatRow: 13,
    seatCol: 15,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 256,
    seatNumber: "M16",
    seatRow: 13,
    seatCol: 16,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 257,
    seatNumber: "M17",
    seatRow: 13,
    seatCol: 17,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 258,
    seatNumber: "M18",
    seatRow: 13,
    seatCol: 18,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 259,
    seatNumber: "M19",
    seatRow: 13,
    seatCol: 19,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 260,
    seatNumber: "M20",
    seatRow: 13,
    seatCol: 20,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 261,
    seatNumber: "N1",
    seatRow: 14,
    seatCol: 1,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 262,
    seatNumber: "N2",
    seatRow: 14,
    seatCol: 2,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 263,
    seatNumber: "N3",
    seatRow: 14,
    seatCol: 3,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 264,
    seatNumber: "N4",
    seatRow: 14,
    seatCol: 4,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 265,
    seatNumber: "N5",
    seatRow: 14,
    seatCol: 5,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 266,
    seatNumber: "N6",
    seatRow: 14,
    seatCol: 6,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 267,
    seatNumber: "N7",
    seatRow: 14,
    seatCol: 7,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 268,
    seatNumber: "N8",
    seatRow: 14,
    seatCol: 8,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 269,
    seatNumber: "N9",
    seatRow: 14,
    seatCol: 9,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 270,
    seatNumber: "N10",
    seatRow: 14,
    seatCol: 10,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 271,
    seatNumber: "N11",
    seatRow: 14,
    seatCol: 11,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 272,
    seatNumber: "N12",
    seatRow: 14,
    seatCol: 12,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 273,
    seatNumber: "N13",
    seatRow: 14,
    seatCol: 13,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 274,
    seatNumber: "N14",
    seatRow: 14,
    seatCol: 14,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 275,
    seatNumber: "N15",
    seatRow: 14,
    seatCol: 15,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 276,
    seatNumber: "N16",
    seatRow: 14,
    seatCol: 16,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 277,
    seatNumber: "N17",
    seatRow: 14,
    seatCol: 17,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 278,
    seatNumber: "N18",
    seatRow: 14,
    seatCol: 18,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 279,
    seatNumber: "N19",
    seatRow: 14,
    seatCol: 19,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 280,
    seatNumber: "N20",
    seatRow: 14,
    seatCol: 20,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 281,
    seatNumber: "O1",
    seatRow: 15,
    seatCol: 1,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 282,
    seatNumber: "O2",
    seatRow: 15,
    seatCol: 2,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 283,
    seatNumber: "O3",
    seatRow: 15,
    seatCol: 3,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 284,
    seatNumber: "O4",
    seatRow: 15,
    seatCol: 4,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 285,
    seatNumber: "O5",
    seatRow: 15,
    seatCol: 5,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 286,
    seatNumber: "O6",
    seatRow: 15,
    seatCol: 6,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 287,
    seatNumber: "O7",
    seatRow: 15,
    seatCol: 7,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 288,
    seatNumber: "O8",
    seatRow: 15,
    seatCol: 8,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 289,
    seatNumber: "O9",
    seatRow: 15,
    seatCol: 9,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 290,
    seatNumber: "O10",
    seatRow: 15,
    seatCol: 10,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 291,
    seatNumber: "O11",
    seatRow: 15,
    seatCol: 11,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 292,
    seatNumber: "O12",
    seatRow: 15,
    seatCol: 12,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 293,
    seatNumber: "O13",
    seatRow: 15,
    seatCol: 13,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 294,
    seatNumber: "O14",
    seatRow: 15,
    seatCol: 14,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 295,
    seatNumber: "O15",
    seatRow: 15,
    seatCol: 15,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 296,
    seatNumber: "O16",
    seatRow: 15,
    seatCol: 16,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 297,
    seatNumber: "O17",
    seatRow: 15,
    seatCol: 17,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 298,
    seatNumber: "O18",
    seatRow: 15,
    seatCol: 18,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 299,
    seatNumber: "O19",
    seatRow: 15,
    seatCol: 19,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 300,
    seatNumber: "O20",
    seatRow: 15,
    seatCol: 20,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 301,
    seatNumber: "P1",
    seatRow: 16,
    seatCol: 1,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 302,
    seatNumber: "P2",
    seatRow: 16,
    seatCol: 2,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 303,
    seatNumber: "P3",
    seatRow: 16,
    seatCol: 3,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 304,
    seatNumber: "P4",
    seatRow: 16,
    seatCol: 4,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 305,
    seatNumber: "P5",
    seatRow: 16,
    seatCol: 5,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 306,
    seatNumber: "P6",
    seatRow: 16,
    seatCol: 6,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 307,
    seatNumber: "P7",
    seatRow: 16,
    seatCol: 7,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 308,
    seatNumber: "P8",
    seatRow: 16,
    seatCol: 8,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 309,
    seatNumber: "P9",
    seatRow: 16,
    seatCol: 9,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 310,
    seatNumber: "P10",
    seatRow: 16,
    seatCol: 10,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 311,
    seatNumber: "P11",
    seatRow: 16,
    seatCol: 11,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 312,
    seatNumber: "P12",
    seatRow: 16,
    seatCol: 12,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 313,
    seatNumber: "P13",
    seatRow: 16,
    seatCol: 13,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 314,
    seatNumber: "P14",
    seatRow: 16,
    seatCol: 14,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 315,
    seatNumber: "P15",
    seatRow: 16,
    seatCol: 15,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 316,
    seatNumber: "P16",
    seatRow: 16,
    seatCol: 16,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 317,
    seatNumber: "P17",
    seatRow: 16,
    seatCol: 17,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 318,
    seatNumber: "P18",
    seatRow: 16,
    seatCol: 18,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 319,
    seatNumber: "P19",
    seatRow: 16,
    seatCol: 19,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 320,
    seatNumber: "P20",
    seatRow: 16,
    seatCol: 20,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 321,
    seatNumber: "Q1",
    seatRow: 17,
    seatCol: 1,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 322,
    seatNumber: "Q2",
    seatRow: 17,
    seatCol: 2,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 323,
    seatNumber: "Q3",
    seatRow: 17,
    seatCol: 3,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 324,
    seatNumber: "Q4",
    seatRow: 17,
    seatCol: 4,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 325,
    seatNumber: "Q5",
    seatRow: 17,
    seatCol: 5,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 326,
    seatNumber: "Q6",
    seatRow: 17,
    seatCol: 6,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 327,
    seatNumber: "Q7",
    seatRow: 17,
    seatCol: 7,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 328,
    seatNumber: "Q8",
    seatRow: 17,
    seatCol: 8,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 329,
    seatNumber: "Q9",
    seatRow: 17,
    seatCol: 9,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 330,
    seatNumber: "Q10",
    seatRow: 17,
    seatCol: 10,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 331,
    seatNumber: "Q11",
    seatRow: 17,
    seatCol: 11,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 332,
    seatNumber: "Q12",
    seatRow: 17,
    seatCol: 12,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 333,
    seatNumber: "Q13",
    seatRow: 17,
    seatCol: 13,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 334,
    seatNumber: "Q14",
    seatRow: 17,
    seatCol: 14,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 335,
    seatNumber: "Q15",
    seatRow: 17,
    seatCol: 15,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 336,
    seatNumber: "Q16",
    seatRow: 17,
    seatCol: 16,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 337,
    seatNumber: "Q17",
    seatRow: 17,
    seatCol: 17,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 338,
    seatNumber: "Q18",
    seatRow: 17,
    seatCol: 18,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 339,
    seatNumber: "Q19",
    seatRow: 17,
    seatCol: 19,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 340,
    seatNumber: "Q20",
    seatRow: 17,
    seatCol: 20,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 341,
    seatNumber: "R1",
    seatRow: 18,
    seatCol: 1,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 342,
    seatNumber: "R2",
    seatRow: 18,
    seatCol: 2,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 343,
    seatNumber: "R3",
    seatRow: 18,
    seatCol: 3,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 344,
    seatNumber: "R4",
    seatRow: 18,
    seatCol: 4,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 345,
    seatNumber: "R5",
    seatRow: 18,
    seatCol: 5,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 346,
    seatNumber: "R6",
    seatRow: 18,
    seatCol: 6,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 347,
    seatNumber: "R7",
    seatRow: 18,
    seatCol: 7,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 348,
    seatNumber: "R8",
    seatRow: 18,
    seatCol: 8,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 349,
    seatNumber: "R9",
    seatRow: 18,
    seatCol: 9,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 350,
    seatNumber: "R10",
    seatRow: 18,
    seatCol: 10,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 351,
    seatNumber: "R11",
    seatRow: 18,
    seatCol: 11,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 352,
    seatNumber: "R12",
    seatRow: 18,
    seatCol: 12,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 353,
    seatNumber: "R13",
    seatRow: 18,
    seatCol: 13,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 354,
    seatNumber: "R14",
    seatRow: 18,
    seatCol: 14,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 355,
    seatNumber: "R15",
    seatRow: 18,
    seatCol: 15,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 356,
    seatNumber: "R16",
    seatRow: 18,
    seatCol: 16,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 357,
    seatNumber: "R17",
    seatRow: 18,
    seatCol: 17,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 358,
    seatNumber: "R18",
    seatRow: 18,
    seatCol: 18,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 359,
    seatNumber: "R19",
    seatRow: 18,
    seatCol: 19,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 360,
    seatNumber: "R20",
    seatRow: 18,
    seatCol: 20,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 361,
    seatNumber: "S1",
    seatRow: 19,
    seatCol: 1,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 362,
    seatNumber: "S2",
    seatRow: 19,
    seatCol: 2,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 363,
    seatNumber: "S3",
    seatRow: 19,
    seatCol: 3,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 364,
    seatNumber: "S4",
    seatRow: 19,
    seatCol: 4,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 365,
    seatNumber: "S5",
    seatRow: 19,
    seatCol: 5,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 366,
    seatNumber: "S6",
    seatRow: 19,
    seatCol: 6,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 367,
    seatNumber: "S7",
    seatRow: 19,
    seatCol: 7,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 368,
    seatNumber: "S8",
    seatRow: 19,
    seatCol: 8,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 369,
    seatNumber: "S9",
    seatRow: 19,
    seatCol: 9,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 370,
    seatNumber: "S10",
    seatRow: 19,
    seatCol: 10,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 371,
    seatNumber: "S11",
    seatRow: 19,
    seatCol: 11,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 372,
    seatNumber: "S12",
    seatRow: 19,
    seatCol: 12,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 373,
    seatNumber: "S13",
    seatRow: 19,
    seatCol: 13,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 374,
    seatNumber: "S14",
    seatRow: 19,
    seatCol: 14,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 375,
    seatNumber: "S15",
    seatRow: 19,
    seatCol: 15,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 376,
    seatNumber: "S16",
    seatRow: 19,
    seatCol: 16,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 377,
    seatNumber: "S17",
    seatRow: 19,
    seatCol: 17,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 378,
    seatNumber: "S18",
    seatRow: 19,
    seatCol: 18,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 379,
    seatNumber: "S19",
    seatRow: 19,
    seatCol: 19,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 380,
    seatNumber: "S20",
    seatRow: 19,
    seatCol: 20,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 381,
    seatNumber: "T1",
    seatRow: 20,
    seatCol: 1,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 382,
    seatNumber: "T2",
    seatRow: 20,
    seatCol: 2,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 383,
    seatNumber: "T3",
    seatRow: 20,
    seatCol: 3,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 384,
    seatNumber: "T4",
    seatRow: 20,
    seatCol: 4,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 385,
    seatNumber: "T5",
    seatRow: 20,
    seatCol: 5,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 386,
    seatNumber: "T6",
    seatRow: 20,
    seatCol: 6,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 387,
    seatNumber: "T7",
    seatRow: 20,
    seatCol: 7,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 388,
    seatNumber: "T8",
    seatRow: 20,
    seatCol: 8,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 389,
    seatNumber: "T9",
    seatRow: 20,
    seatCol: 9,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 390,
    seatNumber: "T10",
    seatRow: 20,
    seatCol: 10,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 391,
    seatNumber: "T11",
    seatRow: 20,
    seatCol: 11,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 392,
    seatNumber: "T12",
    seatRow: 20,
    seatCol: 12,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 393,
    seatNumber: "T13",
    seatRow: 20,
    seatCol: 13,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 394,
    seatNumber: "T14",
    seatRow: 20,
    seatCol: 14,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 395,
    seatNumber: "T15",
    seatRow: 20,
    seatCol: 15,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 396,
    seatNumber: "T16",
    seatRow: 20,
    seatCol: 16,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 397,
    seatNumber: "T17",
    seatRow: 20,
    seatCol: 17,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 398,
    seatNumber: "T18",
    seatRow: 20,
    seatCol: 18,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 399,
    seatNumber: "T19",
    seatRow: 20,
    seatCol: 19,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
  {
    showSeatMappingId: 400,
    seatNumber: "T20",
    seatRow: 20,
    seatCol: 20,
    seatType: "ELITE",
    seatStatus: "AVAILABLE",
    price: 150.0,
  },
];
